sudo: required
services:
  - docker

before_install:
  - docker build -t maktzan/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true maktzan/react-test npm test

after_success:
  - docker build -t maktzan/multi-client ./client
  - docker build -t maktzan/multi-nginx ./nginx
  - docker build -t maktzan/multi-server ./server
  - docker build -t maktzan/multi-worker ./worker
