sudo: required
services:
  - docker

before_install:
  - docker build -t maktzan/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true maktzan/react-test npm test

after_success:
  - docker build -t maktzan/multi-client ./client
  - docker build -t maktzan/multi-nginx ./nginx
  - docker build -t maktzan/multi-server ./server
  - docker build -t maktzan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push maktzan/multi-client
  - docker push maktzan/multi-nginx
  - docker push maktzan/multi-server
  - docker push maktzan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-211199467426'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
